### ISSUE TITLE
Middleware calls next() multiple times when less contains @import url("...")

### ISSUE THREAD

**Issue by toptensoftware** [emberfeather/less.js-middleware#153]
I've been trying to chase down some issues I've been having with less-middleware and have found that with .less files that contain @import url statements, the middleware's `next()` callback is invoked multiple times for a single request.

To test this, I changed the middleware function ([here](https://github.com/emberfeather/less.js-middleware/blob/master/lib/middleware.js#L150)) so I could log the callbacks:

```Javascript
  // Actual middleware.
  return function(req, res, nextOrig) {

    var next = function(x) {
      console.log("less-middleware next()");
      nextOrig(x);
    }
```

Testing with a .less file like so:

```less
@import url("https://fonts.googleapis.com/css?family=Open+Sans:200,300,400,500,600,700");

body {
  padding: 50px;
  font: 14px "Lucida Grande", Helvetica, Arial, sans-serif;
}

a {
  color: #00B7FF;
}
```

Then using wget to request the .css file (to ensure there's only one request at a time), I'm seeing multiple log entries.

1. The first invocation originates with fs.stat ([here](https://github.com/emberfeather/less.js-middleware/blob/master/lib/middleware.js#L220)), on a bogus path `c:\Users\Brad\Projects\test\https:\fonts.googleapis.com\css?family=Open+Sans:200,300,400,500,600,700"`

2. The second originates from `storeCss` after writing the css file [here](https://github.com/emberfeather/less.js-middleware/blob/master/lib/middleware.js#L122).

Of course calling next() multiple times is causing havoc with the subsequent middleware handlers.

This is happening in less-middleware 3.0.0, but doesn't seem to happen in earlier versions (I tested with 2.2.1).
